### ISSUE TITLE
App crashes when CSM Gunner is equipped with Autocannon

### ISSUE THREAD

**Issue by DevJonny** [KTManager/KTRules#18]
**Describe the bug**
App crashes when I make a Chaos Space Marine Gunner get equipped with an Autocannon.

**To Reproduce**
1. CSM Team
2. Add CSM Gunner
3. Equip Autocannon

**Expected behavior**
Happy days

**Comment by tilteffect** [comment]
I'm pretty sure this was my fault. In weapons.jsonnet:11693, I had a typo WeaponType should be WeaponTypeId. I'm refraining from submitting a fix until I can prove that's the issue by running the RulesTool locally. I'm still having trouble with python in my local environment, but I believe that's the problem if anyone wants to beat me to it.

**Comment by DevJonny** [comment]
@tilteffect what python issues are you having? How familiar are you with Python?

**Comment by DevJonny** [comment]
@tilteffect this looks like an issue I came across when trying to add `Repentia Superior`. I'm not sure it's an issue in the rules, but rather an issue in the code.

**Comment by DevJonny** [comment]
Raised a bug in the KTManagerApp repo: https://github.com/KTManager/KTManagerApp/issues/101

Should be fixed in PR: https://github.com/KTManager/KTManagerApp/pull/102

**Comment by tilteffect** [comment]
@DevJonny I just managed to load the data with the fix and it worked, so I believe it does cause the crash. I noticed you also copied my typo with all the new weapons for Sisters of Battle, so that would explain why you were seeing the same bug.

**Comment by DevJonny** [comment]
@tilteffect I actually was only getting the issue with one particular unit, not all of the SoB. So the typo doesn't actually seem to cause an issues.

There was a bug in the code however, and that was causing an issue with the typo and without. Either way all fixed now! 👍

**Comment by DevJonny** [comment]
@tilteffect just thinking, you're probably right about the typo, and why it SoB wasn't working with `models.jsonnet` which I converted back to regular old `models.json` which then worked without issue. I'll try and have a play later, but will fix up the SoB weapon options in `weapons.jsonnet` regardless.
