### ISSUE TITLE
Drukhari Wrack profile does not use errata'd values

### ISSUE THREAD

**Issue by tilteffect** [KTManager/KTRules#21]
**Describe the bug**
The profile for the Drukhari Wrack uses the values found in the Elites book, these values were errata'd

**To Reproduce**
1. Create a Drukari team
2. Add any Wrack member (Wrack, Wrack Gunner, Acothyst).

**Expected behavior**
The profile should be the errata'd one

**Screenshots**
![image](https://user-images.githubusercontent.com/8003898/77239482-1f8fa300-6bd3-11ea-9dee-a769e9536184.png)

**Comment by jakemco** [comment]
The Annual is the latest source of truth, we should use the numbers there (which are more than likely the same as in the errata)

**Comment by Bnorus** [comment]
The Annual updated new teams values, and overall points balance. But those Dark Eldars are showing only on the Erratas from here: https://www.warhammer-community.com/2019/08/23/warhammer-40000-kill-team-updatesgw-homepage-post-3/
