### ISSUE TITLE
[Tyranids] Death spitters for warriors costs 5 instead of 2

### ISSUE THREAD

**Issue by lacombet** [KTManager/KTRules#7]
**Screenshots**

![image](https://user-images.githubusercontent.com/16901080/76536004-0b81ce00-647c-11ea-90b0-ad450883bac6.png)

**Comment by jakemco** [comment]
That picture is from the core book, notes from the annual: Tyranid prime and Ravener should have a 5 cost deathspitter, but warriors should still have cost 2.

**Comment by lacombet** [comment]
this makes this issue even more relevant :

https://github.com/KTManager/KTManagerApp/issues/10

**Comment by Bnorus** [comment]
![image](https://user-images.githubusercontent.com/5378304/76729703-be13a280-6794-11ea-9c95-c256f27c6834.png)
These are the points for the KT Annual 2019.
